"""empty message

Revision ID: 15db72513733
Revises: 
Create Date: 2018-10-19 13:58:23.153618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15db72513733'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['traited.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['traited.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot_x_data',
    sa.Column('snap_id', sa.Integer(), nullable=False),
    sa.Column('snap_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snap_data_id'], ['data_block.id'], ),
    sa.ForeignKeyConstraint(['snap_id'], ['snapshot.id'], ),
    sa.PrimaryKeyConstraint('snap_id', 'snap_data_id')
    )
    op.create_table('snapshot_x_result',
    sa.Column('snap_id', sa.Integer(), nullable=False),
    sa.Column('snap_result_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snap_id'], ['snapshot.id'], ),
    sa.ForeignKeyConstraint(['snap_result_id'], ['result.id'], ),
    sa.PrimaryKeyConstraint('snap_id', 'snap_result_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot_x_result')
    op.drop_table('snapshot_x_data')
    op.drop_table('snapshot')
    op.drop_table('result')
    op.drop_table('data_block')
    # ### end Alembic commands ###
